global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Data;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Net.Mail;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Controls.Primitives;
global using System.Windows.Data;
global using System.Xml.Serialization;
global using AgentFastAdmin;
global using AmbienceLib;
global using DB.QStats.Std.Models;
global using EF.DbHelper.Lib;
global using Emailing;
global using GigaHunt;
global using GigaHunt.AsLink;
global using GigaHunt.Helpers;
global using GigaHunt.Properties;
global using GigaHunt.View;
global using Microsoft.Data.SqlClient;
global using Microsoft.EntityFrameworkCore;
global using OutlookToDbWpfApp;
global using WpfUserControlLib.Extensions;
global using WpfUserControlLib.Helpers;
global using static System.Diagnostics.Trace;
global using OL = Microsoft.Office.Interop.Outlook;
//obal using System.Text.Json; //tu: new and very performant Json lib (Dec 2021)
global using StandardLib.Helpers;