// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.QStats.PwrT.Models;

public partial class AgentOfInterestBySentQntView
{
    public string EmailId { get; set; }

    public int? TtlSent { get; set; }

    public DateTime? LastSent { get; set; }
}