// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.QStats.PwrT.Models;

public partial class Agency
{
    public string Id { get; set; }

    public int? TtlAgents { get; set; }

    public string Address { get; set; }

    public bool IsBroadcastee { get; set; }

    public string Note { get; set; }

    public DateTime AddedAt { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public virtual ICollection<Email> Emails { get; set; } = new List<Email>();

    public virtual ICollection<PhoneAgencyXref> PhoneAgencyXrefs { get; set; } = new List<PhoneAgencyXref>();
}