// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.QStats.PwrT.Models;

public partial class Campaign
{
    public int Id { get; set; }

    public DateTime CampaignStart { get; set; }

    public DateTime? CampaignEnd { get; set; }

    public string Result { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<Email> Emails { get; set; } = new List<Email>();

    public virtual ICollection<Lead> Leads { get; set; } = new List<Lead>();
}