// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.QStats.PwrT.Models;

public partial class ContactRecentActivityView
{
    public DateTime AddedAt { get; set; }

    public string Fname { get; set; }

    public string Lname { get; set; }

    public string Email { get; set; }

    public DateTime? LastSent { get; set; }

    public DateTime? LastRcvd { get; set; }

    public string LastSubject { get; set; }

    public string Notes { get; set; }
}