// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.QStats.PwrT.Models;

public partial class CountryOfOrigin
{
    public string Country { get; set; }

    public string CountryName { get; set; }

    public float Probability { get; set; }

    public string ContinentalRegion { get; set; }

    public string StatisticalRegion { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ChangedAt { get; set; }

    public string FirstnameRootObjectname { get; set; }

    public virtual ICollection<FirstnameCountryXref> FirstnameCountryXrefs { get; set; } = new List<FirstnameCountryXref>();
}