// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.QStats.PwrT.Models;

public partial class Email
{
    public string Id { get; set; }

    public string Fname { get; set; }

    public string Lname { get; set; }

    public string Company { get; set; }

    public string Country { get; set; }

    public string Phone { get; set; }

    public string PermBanReason { get; set; }

    public int? DoNotNotifyOnAvailableForCampaignId { get; set; }

    public int? DoNotNotifyOnOffMarketForCampaignId { get; set; }

    public string Notes { get; set; }

    public int NotifyPriority { get; set; }

    public DateTime? ReSendAfter { get; set; }

    public DateTime? LastAction { get; set; }

    public DateTime AddedAt { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public virtual Agency CompanyNavigation { get; set; }

    public virtual Campaign DoNotNotifyOnOffMarketForCampaign { get; set; }

    public virtual ICollection<Ehist> Ehists { get; set; } = new List<Ehist>();

    public virtual ICollection<LeadEmail> LeadEmails { get; set; } = new List<LeadEmail>();

    public virtual ICollection<Lead> Leads { get; set; } = new List<Lead>();

    public virtual ICollection<PhoneEmailXref> PhoneEmailXrefs { get; set; } = new List<PhoneEmailXref>();
}