// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.QStats.PwrT.Models;

public partial class FirstnameCountryXref
{
    public int Id { get; set; }

    public float Probability { get; set; }

    public string Note { get; set; }

    public string Country { get; set; }

    public string Name { get; set; }

    public virtual CountryOfOrigin CountryNavigation { get; set; }

    public virtual FirstnameRootObject NameNavigation { get; set; }
}