// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DB.QStats.PwrT.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DB.QStats.PwrT.Models
{
    public partial interface IQStatsRlsContextProcedures
    {
        Task<List<GetTotalViewsForThePeriodResult>> GetTotalViewsForThePeriodAsync(int? a, int? b, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
