// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.QStats.PwrT.Models;

public partial class LkuLeadStatus
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Lead> Leads { get; set; } = new List<Lead>();
}