// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.QStats.PwrT.Models;

public partial class OppContactFor
{
    public int Id { get; set; }

    public string Expr1 { get; set; }
}