// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.QStats.PwrT.Models;

public partial class Phone
{
    public int Id { get; set; }

    public string PhoneNumber { get; set; }

    public DateTime SeenFirst { get; set; }

    public DateTime SeenLast { get; set; }

    public string Notes { get; set; }

    public DateTime AddedAt { get; set; }

    public virtual ICollection<PhoneAgencyXref> PhoneAgencyXrefs { get; set; } = new List<PhoneAgencyXref>();

    public virtual ICollection<PhoneEmailXref> PhoneEmailXrefs { get; set; } = new List<PhoneEmailXref>();
}