// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using DB.QStats.PwrT.Models;

namespace DB.QStats.PwrT.Models
{
    public partial class QstatsRlsContext
    {

        [DbFunction("BadEmails", "dbo")]
        public IQueryable<BadEmailsResult> BadEmails()
        {
            return FromExpression(() => BadEmails());
        }

        [DbFunction("CurrentCampaignID", "dbo")]
        public static int? CurrentCampaignID()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        public async Task<int?> CurrentCampaignIDAsync()
            => await Database.SqlQueryRaw<int?>("select Value = [dbo].[CurrentCampaignID]()").SingleAsync();

        [DbFunction("CurrentCampaignStart", "dbo")]
        public static DateTime? CurrentCampaignStart()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        public async Task<DateTime?> CurrentCampaignStartAsync()
            => await Database.SqlQueryRaw<DateTime?>("select Value = [dbo].[CurrentCampaignStart]()").SingleAsync();

        [DbFunction("DateToYYMMDD", "dbo")]
        public static int? DateToYYMMDD(DateTime? InputDate)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("IsNotifiedForCurCmpgn", "dbo")]
        public static bool? IsNotifiedForCurCmpgn(string EmailID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BadEmailsResult>().HasNoKey();
        }
    }
}
