// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DB.QStats.PwrT.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DB.QStats.PwrT.Models
{
    public partial class QstatsRlsContext
    {
        private IQStatsRlsContextProcedures _procedures;

        public virtual IQStatsRlsContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new QStatsRlsContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IQStatsRlsContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class QStatsRlsContextProcedures : IQStatsRlsContextProcedures
    {
        private readonly QstatsRlsContext _context;

        public QStatsRlsContextProcedures(QstatsRlsContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetTotalViewsForThePeriodResult>> GetTotalViewsForThePeriodAsync(int? a, int? b, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "a",
                    Value = a ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "b",
                    Value = b ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetTotalViewsForThePeriodResult>("EXEC @returnValue = [dbo].[GetTotalViewsForThePeriod] @a = @a, @b = @b", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
