global using System;
global using System.ComponentModel;
global using System.Data;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Net.Mail;
global using System.Net.Mime;
global using System.Runtime.InteropServices;
global using System.Security.Principal;
global using System.Text;
//obal using System.Text.Json; //tu: new and very performant Json lib (Dec 2021)
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using DB.QStats.Std.Models;
global using EF.DbHelper.Lib;
global using GigaHunt.Helpers;
global using GigaHunt.View;
global using Microsoft.EntityFrameworkCore;
global using OutlookToDbWpfApp;
global using WpfUserControlLib.Extensions;
global using static System.Diagnostics.Trace;
global using OL = Microsoft.Office.Interop.Outlook;
