global using DB.QStats.Std.Models;
global using EF.DbHelper.Lib;
global using Emailing.NET6.Helpers;
global using GigaHunt.View;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using PhoneAreaCoder;
global using StandardLib.Extensions;
global using System;
global using System.ComponentModel;
global using System.Data;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Net.Mail;
global using System.Runtime.InteropServices;
global using System.Security.Principal;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using static System.Diagnostics.Trace;
global using OL = Microsoft.Office.Interop.Outlook;
